In [24]:
import tensorflow
import numpy

# What is TensorFlow?
-> TensorFlow is an open source machine learning platform. This platform allows us to create AI models, image classification, data clustering, regression, feinforcement learning and natural language processing. The things you can do with TensorFlow is pretty much everything you need to do everything with Machine Learning (ML).

Observation: TensorFlow is owned and maintianed by Google.

# TensorFlow Foundations (Graphs)
I.E.: Data structure that defines the computation you want to perform. Every operation like summing, dividing, calculating the loss function or running gradient descent is first added as a node in this graph. Only after the graph is built TensorFlow executes it, usually in a session.

This differs from typical imperative programming, where the computer performs computations immediately, step by step, often using low-level binary arithmetic. In TensorFlow you first describe the computation as a graph and then run it to get results.

# TensorFlow Foundations (Session)
-> A Session is the runtime environment that executes the computation graph. The session handle things like: Alocating memory, running operations on CPUs or GPUs and fetching outputs.

# What are Tensors?
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes."

In other words, a tensor is a data structure that can represent a scalar, a vector, a matrix, or higher-dimensional arrays, depending on the number of dimensions it has. To define a Tensor, you must define the Data Type (float32, int32, string and others) and the shape of it.




In [25]:
# Creating Tensors:
stringTensor = tensorflow.Variable("Value", tensorflow.string) # Type: string
intTensor = tensorflow.Variable(1, tensorflow.int32) # Type: Integer of 32 bits
floatTensor = tensorflow.Variable(1.2, tensorflow.float64) # Type: float of 64 bits

#Observation: You can define the amount of bits after the type
# Syntax: varName = tensorflow.Variable(value, tensorflow.typeBits)

# The Shape of a Tensor
-> Think of a Tensor as a container, and its shape describes its structure. For example, a Tensor with the value [[2, 2], [2, 2]] has the shape (2, 2), meaning it has 2 rows and 2 columns. The product of the shape’s dimensions (2 × 2) tells us the total number of elements stored in the Tensor.

In [26]:
# It is possible to find the Shape of a Tensor by the method:
shape321 = tensorflow.Variable([[[1],[2]], [[3],[4]], [[5],[6]]], tensorflow.int32) # Tensor of shape (3,2,1)
shape321.shape

TensorShape([3, 2, 1])

# The Rank/Degree of a Tensor
The rank / Degree of a Tensor means how many dimensions it has. If there is only 1 value into the Tensor, it will be a Scalar, so the rank/degree is 0, respectvely. Continuing with this idea, if the value represents a vector, the rank should be 1, since it will have only 1 dimension.

List of values and the correspondenting rank/degree:
<table>
    <th>Value</th>
    <th>Rank</th>
    <tr><td>2</td><td>0</td></tr>
    <tr><td>[2,2]</td><td>1</td></tr>
    <tr><td>[[2,2],[2,2]]</td>2<td>2</td></tr>
    <tr><td>[[2,2],[2,2],[2,2]]</td><td>2</td></tr>
    <tr><td>[[[2,2],[2,2],[2,2]],[[2,2],[2,2],[2,2]]]</td><td>3</td></tr>
    <tr><td>[[[2,2,2,2],[2,2,2,2],[2,2,2,2]],[[2,2,2,2],[2,2,2,2],[2,2,2,2]]]</td><td>3</td></tr>
    <tr><td>[2,2,2,2,2,2]</td><td>1</td></tr>
</table>

Tip: Count the amount of opening bracks before the first number, it also indicates the rank/degree

In [27]:
# Also, to find the rank/degree of a Tensor, we can use the method:
threeDegreesTensor = tensorflow.Variable([[[2,2],[2,2],[2,2]],[[2,2],[2,2],[2,2]]], tensorflow.int32) # Rank 3 Tensor
tensorflow.rank(threeDegreesTensor) # The output as "numpy" indicates the Rank.

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# Reshaping a Tensor
It is possible to change the shape of a Tensor by the method.
Syntax explanation: tensorflow.reshape(tensorToReshape, newShape)

Observation: The amount of elements before and afeter reshaping must be the same.

In [32]:
#Example:
tensorflow.reshape(shape321, [3,2])
tensorflow.reshape(shape321, [3, -1]) # -1 asks the TensorFlow to calculate the possible value for it.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

# Types of Tensors
Variable: The only mutable Tensor available for creating.
Constant: Behaves like the variable (they are pretty much the same), what changes is that it becames immutable.
SparseTensor: Represents Tensors that have mostly zero (or default) values. It stores: 1- Indices of the non-zero values, where they will be located; 2- The zero values, 3- The shape of the Tensor

In [ ]:
# Creating more Tensors:
sparseTensor = tensorflow.sparse.SparseTensor(
    indices=[[0,0],[1,2]], # List of the non-zero values indices
    values=[3,7], # Indices of zeroes
    dense_shape=[3,4] # The shape of the Tensor
)

constantTensor = tensorflow.constant([1,1,1], dtype=tensorflow.int3)